# Generated by Django 4.2.7 on 2024-01-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_conversation_conversationmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
    ]
